// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/ai_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 预测模式
type PredictRequest_Mode int32

const (
	PredictRequest_BASIC    PredictRequest_Mode = 0 // 基础优化（规则引擎）
	PredictRequest_ADVANCED PredictRequest_Mode = 1 // 高级AI（SWT+LightGBM+贝叶斯）
	PredictRequest_HYBRID   PredictRequest_Mode = 2 // 混合模式（智能路由）
)

// Enum value maps for PredictRequest_Mode.
var (
	PredictRequest_Mode_name = map[int32]string{
		0: "BASIC",
		1: "ADVANCED",
		2: "HYBRID",
	}
	PredictRequest_Mode_value = map[string]int32{
		"BASIC":    0,
		"ADVANCED": 1,
		"HYBRID":   2,
	}
)

func (x PredictRequest_Mode) Enum() *PredictRequest_Mode {
	p := new(PredictRequest_Mode)
	*p = x
	return p
}

func (x PredictRequest_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PredictRequest_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ai_service_proto_enumTypes[0].Descriptor()
}

func (PredictRequest_Mode) Type() protoreflect.EnumType {
	return &file_proto_ai_service_proto_enumTypes[0]
}

func (x PredictRequest_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PredictRequest_Mode.Descriptor instead.
func (PredictRequest_Mode) EnumDescriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{0, 0}
}

// ==================== 预测请求 ====================
type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          PredictRequest_Mode    `protobuf:"varint,1,opt,name=mode,proto3,enum=pixly.ai.PredictRequest_Mode" json:"mode,omitempty"`
	Image         *ImageInfo             `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Tool          string                 `protobuf:"bytes,3,opt,name=tool,proto3" json:"tool,omitempty"` // cjxl/ffmpeg/avifenc/cwebp
	Options       *PredictOptions        `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_proto_ai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetMode() PredictRequest_Mode {
	if x != nil {
		return x.Mode
	}
	return PredictRequest_BASIC
}

func (x *PredictRequest) GetImage() *ImageInfo {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *PredictRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *PredictRequest) GetOptions() *PredictOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// ==================== 图像信息 ====================
type ImageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"` // jpg/png/webp/gif...
	IsAnimated    bool                   `protobuf:"varint,6,opt,name=is_animated,json=isAnimated,proto3" json:"is_animated,omitempty"`
	HasAlpha      bool                   `protobuf:"varint,7,opt,name=has_alpha,json=hasAlpha,proto3" json:"has_alpha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	mi := &file_proto_ai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{1}
}

func (x *ImageInfo) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ImageInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImageInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ImageInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ImageInfo) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ImageInfo) GetIsAnimated() bool {
	if x != nil {
		return x.IsAnimated
	}
	return false
}

func (x *ImageInfo) GetHasAlpha() bool {
	if x != nil {
		return x.HasAlpha
	}
	return false
}

// ==================== 预测选项 ====================
type PredictOptions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TargetFormat    string                 `protobuf:"bytes,1,opt,name=target_format,json=targetFormat,proto3" json:"target_format,omitempty"`             // 目标格式
	EnableBayesian  bool                   `protobuf:"varint,2,opt,name=enable_bayesian,json=enableBayesian,proto3" json:"enable_bayesian,omitempty"`      // 启用贝叶斯优化
	MaxIterations   int32                  `protobuf:"varint,3,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`         // 贝叶斯最大迭代次数
	EnableSsimCheck bool                   `protobuf:"varint,4,opt,name=enable_ssim_check,json=enableSsimCheck,proto3" json:"enable_ssim_check,omitempty"` // 启用SSIM验证
	SsimThreshold   float32                `protobuf:"fixed32,5,opt,name=ssim_threshold,json=ssimThreshold,proto3" json:"ssim_threshold,omitempty"`        // SSIM阈值（默认0.95）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PredictOptions) Reset() {
	*x = PredictOptions{}
	mi := &file_proto_ai_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictOptions) ProtoMessage() {}

func (x *PredictOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictOptions.ProtoReflect.Descriptor instead.
func (*PredictOptions) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{2}
}

func (x *PredictOptions) GetTargetFormat() string {
	if x != nil {
		return x.TargetFormat
	}
	return ""
}

func (x *PredictOptions) GetEnableBayesian() bool {
	if x != nil {
		return x.EnableBayesian
	}
	return false
}

func (x *PredictOptions) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *PredictOptions) GetEnableSsimCheck() bool {
	if x != nil {
		return x.EnableSsimCheck
	}
	return false
}

func (x *PredictOptions) GetSsimThreshold() float32 {
	if x != nil {
		return x.SsimThreshold
	}
	return 0
}

// ==================== 预测响应 ====================
type PredictResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Params               *ToolParams            `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	EstimatedSize        int64                  `protobuf:"varint,2,opt,name=estimated_size,json=estimatedSize,proto3" json:"estimated_size,omitempty"`
	EstimatedCompression float32                `protobuf:"fixed32,3,opt,name=estimated_compression,json=estimatedCompression,proto3" json:"estimated_compression,omitempty"`
	Confidence           float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	SsimEstimate         float32                `protobuf:"fixed32,5,opt,name=ssim_estimate,json=ssimEstimate,proto3" json:"ssim_estimate,omitempty"`
	PredictionTimeMs     float32                `protobuf:"fixed32,6,opt,name=prediction_time_ms,json=predictionTimeMs,proto3" json:"prediction_time_ms,omitempty"`
	ModeUsed             string                 `protobuf:"bytes,7,opt,name=mode_used,json=modeUsed,proto3" json:"mode_used,omitempty"`
	Reason               string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_proto_ai_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{3}
}

func (x *PredictResponse) GetParams() *ToolParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *PredictResponse) GetEstimatedSize() int64 {
	if x != nil {
		return x.EstimatedSize
	}
	return 0
}

func (x *PredictResponse) GetEstimatedCompression() float32 {
	if x != nil {
		return x.EstimatedCompression
	}
	return 0
}

func (x *PredictResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *PredictResponse) GetSsimEstimate() float32 {
	if x != nil {
		return x.SsimEstimate
	}
	return 0
}

func (x *PredictResponse) GetPredictionTimeMs() float32 {
	if x != nil {
		return x.PredictionTimeMs
	}
	return 0
}

func (x *PredictResponse) GetModeUsed() string {
	if x != nil {
		return x.ModeUsed
	}
	return ""
}

func (x *PredictResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ==================== 工具参数 ====================
type ToolParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cjxl 参数
	CjxlQuality     int32   `protobuf:"varint,1,opt,name=cjxl_quality,json=cjxlQuality,proto3" json:"cjxl_quality,omitempty"`
	CjxlEffort      int32   `protobuf:"varint,2,opt,name=cjxl_effort,json=cjxlEffort,proto3" json:"cjxl_effort,omitempty"`
	CjxlDistance    float32 `protobuf:"fixed32,3,opt,name=cjxl_distance,json=cjxlDistance,proto3" json:"cjxl_distance,omitempty"`
	CjxlLossless    bool    `protobuf:"varint,4,opt,name=cjxl_lossless,json=cjxlLossless,proto3" json:"cjxl_lossless,omitempty"`
	CjxlModular     bool    `protobuf:"varint,5,opt,name=cjxl_modular,json=cjxlModular,proto3" json:"cjxl_modular,omitempty"`
	CjxlProgressive bool    `protobuf:"varint,6,opt,name=cjxl_progressive,json=cjxlProgressive,proto3" json:"cjxl_progressive,omitempty"`
	// avifenc 参数
	AvifQuantizer      int32 `protobuf:"varint,10,opt,name=avif_quantizer,json=avifQuantizer,proto3" json:"avif_quantizer,omitempty"`
	AvifQuantizerAlpha int32 `protobuf:"varint,11,opt,name=avif_quantizer_alpha,json=avifQuantizerAlpha,proto3" json:"avif_quantizer_alpha,omitempty"`
	AvifSpeed          int32 `protobuf:"varint,12,opt,name=avif_speed,json=avifSpeed,proto3" json:"avif_speed,omitempty"`
	// cwebp 参数
	WebpQuality  int32 `protobuf:"varint,20,opt,name=webp_quality,json=webpQuality,proto3" json:"webp_quality,omitempty"`
	WebpMethod   int32 `protobuf:"varint,21,opt,name=webp_method,json=webpMethod,proto3" json:"webp_method,omitempty"`
	WebpLossless bool  `protobuf:"varint,22,opt,name=webp_lossless,json=webpLossless,proto3" json:"webp_lossless,omitempty"`
	// ffmpeg 参数
	FfmpegCrf     int32  `protobuf:"varint,30,opt,name=ffmpeg_crf,json=ffmpegCrf,proto3" json:"ffmpeg_crf,omitempty"`
	FfmpegPreset  string `protobuf:"bytes,31,opt,name=ffmpeg_preset,json=ffmpegPreset,proto3" json:"ffmpeg_preset,omitempty"` // ultrafast/fast/medium/slow/slower/veryslow
	FfmpegCodec   string `protobuf:"bytes,32,opt,name=ffmpeg_codec,json=ffmpegCodec,proto3" json:"ffmpeg_codec,omitempty"`    // libx264/libx265/libsvtav1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolParams) Reset() {
	*x = ToolParams{}
	mi := &file_proto_ai_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolParams) ProtoMessage() {}

func (x *ToolParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolParams.ProtoReflect.Descriptor instead.
func (*ToolParams) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{4}
}

func (x *ToolParams) GetCjxlQuality() int32 {
	if x != nil {
		return x.CjxlQuality
	}
	return 0
}

func (x *ToolParams) GetCjxlEffort() int32 {
	if x != nil {
		return x.CjxlEffort
	}
	return 0
}

func (x *ToolParams) GetCjxlDistance() float32 {
	if x != nil {
		return x.CjxlDistance
	}
	return 0
}

func (x *ToolParams) GetCjxlLossless() bool {
	if x != nil {
		return x.CjxlLossless
	}
	return false
}

func (x *ToolParams) GetCjxlModular() bool {
	if x != nil {
		return x.CjxlModular
	}
	return false
}

func (x *ToolParams) GetCjxlProgressive() bool {
	if x != nil {
		return x.CjxlProgressive
	}
	return false
}

func (x *ToolParams) GetAvifQuantizer() int32 {
	if x != nil {
		return x.AvifQuantizer
	}
	return 0
}

func (x *ToolParams) GetAvifQuantizerAlpha() int32 {
	if x != nil {
		return x.AvifQuantizerAlpha
	}
	return 0
}

func (x *ToolParams) GetAvifSpeed() int32 {
	if x != nil {
		return x.AvifSpeed
	}
	return 0
}

func (x *ToolParams) GetWebpQuality() int32 {
	if x != nil {
		return x.WebpQuality
	}
	return 0
}

func (x *ToolParams) GetWebpMethod() int32 {
	if x != nil {
		return x.WebpMethod
	}
	return 0
}

func (x *ToolParams) GetWebpLossless() bool {
	if x != nil {
		return x.WebpLossless
	}
	return false
}

func (x *ToolParams) GetFfmpegCrf() int32 {
	if x != nil {
		return x.FfmpegCrf
	}
	return 0
}

func (x *ToolParams) GetFfmpegPreset() string {
	if x != nil {
		return x.FfmpegPreset
	}
	return ""
}

func (x *ToolParams) GetFfmpegCodec() string {
	if x != nil {
		return x.FfmpegCodec
	}
	return ""
}

// ==================== 批量预测 ====================
type PredictBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          PredictRequest_Mode    `protobuf:"varint,1,opt,name=mode,proto3,enum=pixly.ai.PredictRequest_Mode" json:"mode,omitempty"`
	Images        []*ImageInfo           `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	Tool          string                 `protobuf:"bytes,3,opt,name=tool,proto3" json:"tool,omitempty"`
	Options       *PredictOptions        `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictBatchRequest) Reset() {
	*x = PredictBatchRequest{}
	mi := &file_proto_ai_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictBatchRequest) ProtoMessage() {}

func (x *PredictBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictBatchRequest.ProtoReflect.Descriptor instead.
func (*PredictBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{5}
}

func (x *PredictBatchRequest) GetMode() PredictRequest_Mode {
	if x != nil {
		return x.Mode
	}
	return PredictRequest_BASIC
}

func (x *PredictBatchRequest) GetImages() []*ImageInfo {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *PredictBatchRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *PredictBatchRequest) GetOptions() *PredictOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type PredictBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PredictResponse     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	TotalTimeMs   float32                `protobuf:"fixed32,2,opt,name=total_time_ms,json=totalTimeMs,proto3" json:"total_time_ms,omitempty"`
	SuccessCount  int32                  `protobuf:"varint,3,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailedCount   int32                  `protobuf:"varint,4,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictBatchResponse) Reset() {
	*x = PredictBatchResponse{}
	mi := &file_proto_ai_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictBatchResponse) ProtoMessage() {}

func (x *PredictBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictBatchResponse.ProtoReflect.Descriptor instead.
func (*PredictBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{6}
}

func (x *PredictBatchResponse) GetResults() []*PredictResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *PredictBatchResponse) GetTotalTimeMs() float32 {
	if x != nil {
		return x.TotalTimeMs
	}
	return 0
}

func (x *PredictBatchResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *PredictBatchResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

// ==================== 质量评估 ====================
type AssessRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OriginalPath   string                 `protobuf:"bytes,1,opt,name=original_path,json=originalPath,proto3" json:"original_path,omitempty"`
	CompressedPath string                 `protobuf:"bytes,2,opt,name=compressed_path,json=compressedPath,proto3" json:"compressed_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssessRequest) Reset() {
	*x = AssessRequest{}
	mi := &file_proto_ai_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessRequest) ProtoMessage() {}

func (x *AssessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessRequest.ProtoReflect.Descriptor instead.
func (*AssessRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{7}
}

func (x *AssessRequest) GetOriginalPath() string {
	if x != nil {
		return x.OriginalPath
	}
	return ""
}

func (x *AssessRequest) GetCompressedPath() string {
	if x != nil {
		return x.CompressedPath
	}
	return ""
}

type AssessResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Ssim              float32                `protobuf:"fixed32,1,opt,name=ssim,proto3" json:"ssim,omitempty"`
	Psnr              float32                `protobuf:"fixed32,2,opt,name=psnr,proto3" json:"psnr,omitempty"`
	PerceptualQuality float32                `protobuf:"fixed32,3,opt,name=perceptual_quality,json=perceptualQuality,proto3" json:"perceptual_quality,omitempty"`
	CompressionRatio  float32                `protobuf:"fixed32,4,opt,name=compression_ratio,json=compressionRatio,proto3" json:"compression_ratio,omitempty"`
	OriginalSize      int64                  `protobuf:"varint,5,opt,name=original_size,json=originalSize,proto3" json:"original_size,omitempty"`
	CompressedSize    int64                  `protobuf:"varint,6,opt,name=compressed_size,json=compressedSize,proto3" json:"compressed_size,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AssessResponse) Reset() {
	*x = AssessResponse{}
	mi := &file_proto_ai_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessResponse) ProtoMessage() {}

func (x *AssessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessResponse.ProtoReflect.Descriptor instead.
func (*AssessResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{8}
}

func (x *AssessResponse) GetSsim() float32 {
	if x != nil {
		return x.Ssim
	}
	return 0
}

func (x *AssessResponse) GetPsnr() float32 {
	if x != nil {
		return x.Psnr
	}
	return 0
}

func (x *AssessResponse) GetPerceptualQuality() float32 {
	if x != nil {
		return x.PerceptualQuality
	}
	return 0
}

func (x *AssessResponse) GetCompressionRatio() float32 {
	if x != nil {
		return x.CompressionRatio
	}
	return 0
}

func (x *AssessResponse) GetOriginalSize() int64 {
	if x != nil {
		return x.OriginalSize
	}
	return 0
}

func (x *AssessResponse) GetCompressedSize() int64 {
	if x != nil {
		return x.CompressedSize
	}
	return 0
}

// ==================== 贝叶斯优化 ====================
type OptimizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *ImageInfo             `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Tool          string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	InitialParams *ToolParams            `protobuf:"bytes,3,opt,name=initial_params,json=initialParams,proto3" json:"initial_params,omitempty"`
	MaxIterations int32                  `protobuf:"varint,4,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizeRequest) Reset() {
	*x = OptimizeRequest{}
	mi := &file_proto_ai_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeRequest) ProtoMessage() {}

func (x *OptimizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeRequest.ProtoReflect.Descriptor instead.
func (*OptimizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{9}
}

func (x *OptimizeRequest) GetImage() *ImageInfo {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *OptimizeRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *OptimizeRequest) GetInitialParams() *ToolParams {
	if x != nil {
		return x.InitialParams
	}
	return nil
}

func (x *OptimizeRequest) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

type OptimizeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OptimizedParams *ToolParams            `protobuf:"bytes,1,opt,name=optimized_params,json=optimizedParams,proto3" json:"optimized_params,omitempty"`
	BestScore       float32                `protobuf:"fixed32,2,opt,name=best_score,json=bestScore,proto3" json:"best_score,omitempty"`
	IterationsUsed  int32                  `protobuf:"varint,3,opt,name=iterations_used,json=iterationsUsed,proto3" json:"iterations_used,omitempty"`
	History         []*OptimizationStep    `protobuf:"bytes,4,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OptimizeResponse) Reset() {
	*x = OptimizeResponse{}
	mi := &file_proto_ai_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeResponse) ProtoMessage() {}

func (x *OptimizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeResponse.ProtoReflect.Descriptor instead.
func (*OptimizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{10}
}

func (x *OptimizeResponse) GetOptimizedParams() *ToolParams {
	if x != nil {
		return x.OptimizedParams
	}
	return nil
}

func (x *OptimizeResponse) GetBestScore() float32 {
	if x != nil {
		return x.BestScore
	}
	return 0
}

func (x *OptimizeResponse) GetIterationsUsed() int32 {
	if x != nil {
		return x.IterationsUsed
	}
	return 0
}

func (x *OptimizeResponse) GetHistory() []*OptimizationStep {
	if x != nil {
		return x.History
	}
	return nil
}

type OptimizationStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Iteration     int32                  `protobuf:"varint,1,opt,name=iteration,proto3" json:"iteration,omitempty"`
	Params        *ToolParams            `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizationStep) Reset() {
	*x = OptimizationStep{}
	mi := &file_proto_ai_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizationStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizationStep) ProtoMessage() {}

func (x *OptimizationStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizationStep.ProtoReflect.Descriptor instead.
func (*OptimizationStep) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{11}
}

func (x *OptimizationStep) GetIteration() int32 {
	if x != nil {
		return x.Iteration
	}
	return 0
}

func (x *OptimizationStep) GetParams() *ToolParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *OptimizationStep) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// ==================== 健康检查 ====================
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_ai_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{12}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsHealthy     bool                   `protobuf:"varint,1,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ModelsLoaded  bool                   `protobuf:"varint,3,opt,name=models_loaded,json=modelsLoaded,proto3" json:"models_loaded,omitempty"`
	UptimeSeconds int32                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_ai_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{13}
}

func (x *HealthCheckResponse) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetModelsLoaded() bool {
	if x != nil {
		return x.ModelsLoaded
	}
	return false
}

func (x *HealthCheckResponse) GetUptimeSeconds() int32 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_proto_ai_service_proto protoreflect.FileDescriptor

const file_proto_ai_service_proto_rawDesc = "" +
	"\n" +
	"\x16proto/ai_service.proto\x12\bpixly.ai\"\xe3\x01\n" +
	"\x0ePredictRequest\x121\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x1d.pixly.ai.PredictRequest.ModeR\x04mode\x12)\n" +
	"\x05image\x18\x02 \x01(\v2\x13.pixly.ai.ImageInfoR\x05image\x12\x12\n" +
	"\x04tool\x18\x03 \x01(\tR\x04tool\x122\n" +
	"\aoptions\x18\x04 \x01(\v2\x18.pixly.ai.PredictOptionsR\aoptions\"+\n" +
	"\x04Mode\x12\t\n" +
	"\x05BASIC\x10\x00\x12\f\n" +
	"\bADVANCED\x10\x01\x12\n" +
	"\n" +
	"\x06HYBRID\x10\x02\"\xc0\x01\n" +
	"\tImageInfo\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x12\x1f\n" +
	"\vis_animated\x18\x06 \x01(\bR\n" +
	"isAnimated\x12\x1b\n" +
	"\thas_alpha\x18\a \x01(\bR\bhasAlpha\"\xd8\x01\n" +
	"\x0ePredictOptions\x12#\n" +
	"\rtarget_format\x18\x01 \x01(\tR\ftargetFormat\x12'\n" +
	"\x0fenable_bayesian\x18\x02 \x01(\bR\x0eenableBayesian\x12%\n" +
	"\x0emax_iterations\x18\x03 \x01(\x05R\rmaxIterations\x12*\n" +
	"\x11enable_ssim_check\x18\x04 \x01(\bR\x0fenableSsimCheck\x12%\n" +
	"\x0essim_threshold\x18\x05 \x01(\x02R\rssimThreshold\"\xc3\x02\n" +
	"\x0fPredictResponse\x12,\n" +
	"\x06params\x18\x01 \x01(\v2\x14.pixly.ai.ToolParamsR\x06params\x12%\n" +
	"\x0eestimated_size\x18\x02 \x01(\x03R\restimatedSize\x123\n" +
	"\x15estimated_compression\x18\x03 \x01(\x02R\x14estimatedCompression\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\x12#\n" +
	"\rssim_estimate\x18\x05 \x01(\x02R\fssimEstimate\x12,\n" +
	"\x12prediction_time_ms\x18\x06 \x01(\x02R\x10predictionTimeMs\x12\x1b\n" +
	"\tmode_used\x18\a \x01(\tR\bmodeUsed\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\"\xb0\x04\n" +
	"\n" +
	"ToolParams\x12!\n" +
	"\fcjxl_quality\x18\x01 \x01(\x05R\vcjxlQuality\x12\x1f\n" +
	"\vcjxl_effort\x18\x02 \x01(\x05R\n" +
	"cjxlEffort\x12#\n" +
	"\rcjxl_distance\x18\x03 \x01(\x02R\fcjxlDistance\x12#\n" +
	"\rcjxl_lossless\x18\x04 \x01(\bR\fcjxlLossless\x12!\n" +
	"\fcjxl_modular\x18\x05 \x01(\bR\vcjxlModular\x12)\n" +
	"\x10cjxl_progressive\x18\x06 \x01(\bR\x0fcjxlProgressive\x12%\n" +
	"\x0eavif_quantizer\x18\n" +
	" \x01(\x05R\ravifQuantizer\x120\n" +
	"\x14avif_quantizer_alpha\x18\v \x01(\x05R\x12avifQuantizerAlpha\x12\x1d\n" +
	"\n" +
	"avif_speed\x18\f \x01(\x05R\tavifSpeed\x12!\n" +
	"\fwebp_quality\x18\x14 \x01(\x05R\vwebpQuality\x12\x1f\n" +
	"\vwebp_method\x18\x15 \x01(\x05R\n" +
	"webpMethod\x12#\n" +
	"\rwebp_lossless\x18\x16 \x01(\bR\fwebpLossless\x12\x1d\n" +
	"\n" +
	"ffmpeg_crf\x18\x1e \x01(\x05R\tffmpegCrf\x12#\n" +
	"\rffmpeg_preset\x18\x1f \x01(\tR\fffmpegPreset\x12!\n" +
	"\fffmpeg_codec\x18  \x01(\tR\vffmpegCodec\"\xbd\x01\n" +
	"\x13PredictBatchRequest\x121\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x1d.pixly.ai.PredictRequest.ModeR\x04mode\x12+\n" +
	"\x06images\x18\x02 \x03(\v2\x13.pixly.ai.ImageInfoR\x06images\x12\x12\n" +
	"\x04tool\x18\x03 \x01(\tR\x04tool\x122\n" +
	"\aoptions\x18\x04 \x01(\v2\x18.pixly.ai.PredictOptionsR\aoptions\"\xb7\x01\n" +
	"\x14PredictBatchResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.pixly.ai.PredictResponseR\aresults\x12\"\n" +
	"\rtotal_time_ms\x18\x02 \x01(\x02R\vtotalTimeMs\x12#\n" +
	"\rsuccess_count\x18\x03 \x01(\x05R\fsuccessCount\x12!\n" +
	"\ffailed_count\x18\x04 \x01(\x05R\vfailedCount\"]\n" +
	"\rAssessRequest\x12#\n" +
	"\roriginal_path\x18\x01 \x01(\tR\foriginalPath\x12'\n" +
	"\x0fcompressed_path\x18\x02 \x01(\tR\x0ecompressedPath\"\xe2\x01\n" +
	"\x0eAssessResponse\x12\x12\n" +
	"\x04ssim\x18\x01 \x01(\x02R\x04ssim\x12\x12\n" +
	"\x04psnr\x18\x02 \x01(\x02R\x04psnr\x12-\n" +
	"\x12perceptual_quality\x18\x03 \x01(\x02R\x11perceptualQuality\x12+\n" +
	"\x11compression_ratio\x18\x04 \x01(\x02R\x10compressionRatio\x12#\n" +
	"\roriginal_size\x18\x05 \x01(\x03R\foriginalSize\x12'\n" +
	"\x0fcompressed_size\x18\x06 \x01(\x03R\x0ecompressedSize\"\xb4\x01\n" +
	"\x0fOptimizeRequest\x12)\n" +
	"\x05image\x18\x01 \x01(\v2\x13.pixly.ai.ImageInfoR\x05image\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12;\n" +
	"\x0einitial_params\x18\x03 \x01(\v2\x14.pixly.ai.ToolParamsR\rinitialParams\x12%\n" +
	"\x0emax_iterations\x18\x04 \x01(\x05R\rmaxIterations\"\xd1\x01\n" +
	"\x10OptimizeResponse\x12?\n" +
	"\x10optimized_params\x18\x01 \x01(\v2\x14.pixly.ai.ToolParamsR\x0foptimizedParams\x12\x1d\n" +
	"\n" +
	"best_score\x18\x02 \x01(\x02R\tbestScore\x12'\n" +
	"\x0fiterations_used\x18\x03 \x01(\x05R\x0eiterationsUsed\x124\n" +
	"\ahistory\x18\x04 \x03(\v2\x1a.pixly.ai.OptimizationStepR\ahistory\"t\n" +
	"\x10OptimizationStep\x12\x1c\n" +
	"\titeration\x18\x01 \x01(\x05R\titeration\x12,\n" +
	"\x06params\x18\x02 \x01(\v2\x14.pixly.ai.ToolParamsR\x06params\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\"\x14\n" +
	"\x12HealthCheckRequest\"\x9a\x01\n" +
	"\x13HealthCheckResponse\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x01 \x01(\bR\tisHealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12#\n" +
	"\rmodels_loaded\x18\x03 \x01(\bR\fmodelsLoaded\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x05R\ruptimeSeconds2\xf5\x02\n" +
	"\vAIPredictor\x12>\n" +
	"\aPredict\x12\x18.pixly.ai.PredictRequest\x1a\x19.pixly.ai.PredictResponse\x12M\n" +
	"\fPredictBatch\x12\x1d.pixly.ai.PredictBatchRequest\x1a\x1e.pixly.ai.PredictBatchResponse\x12B\n" +
	"\rAssessQuality\x12\x17.pixly.ai.AssessRequest\x1a\x18.pixly.ai.AssessResponse\x12G\n" +
	"\x0eOptimizeParams\x12\x19.pixly.ai.OptimizeRequest\x1a\x1a.pixly.ai.OptimizeResponse\x12J\n" +
	"\vHealthCheck\x12\x1c.pixly.ai.HealthCheckRequest\x1a\x1d.pixly.ai.HealthCheckResponseB\x11Z\x0fpixly/ai/pbb\x06proto3"

var (
	file_proto_ai_service_proto_rawDescOnce sync.Once
	file_proto_ai_service_proto_rawDescData []byte
)

func file_proto_ai_service_proto_rawDescGZIP() []byte {
	file_proto_ai_service_proto_rawDescOnce.Do(func() {
		file_proto_ai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_service_proto_rawDesc), len(file_proto_ai_service_proto_rawDesc)))
	})
	return file_proto_ai_service_proto_rawDescData
}

var file_proto_ai_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_ai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_ai_service_proto_goTypes = []any{
	(PredictRequest_Mode)(0),     // 0: pixly.ai.PredictRequest.Mode
	(*PredictRequest)(nil),       // 1: pixly.ai.PredictRequest
	(*ImageInfo)(nil),            // 2: pixly.ai.ImageInfo
	(*PredictOptions)(nil),       // 3: pixly.ai.PredictOptions
	(*PredictResponse)(nil),      // 4: pixly.ai.PredictResponse
	(*ToolParams)(nil),           // 5: pixly.ai.ToolParams
	(*PredictBatchRequest)(nil),  // 6: pixly.ai.PredictBatchRequest
	(*PredictBatchResponse)(nil), // 7: pixly.ai.PredictBatchResponse
	(*AssessRequest)(nil),        // 8: pixly.ai.AssessRequest
	(*AssessResponse)(nil),       // 9: pixly.ai.AssessResponse
	(*OptimizeRequest)(nil),      // 10: pixly.ai.OptimizeRequest
	(*OptimizeResponse)(nil),     // 11: pixly.ai.OptimizeResponse
	(*OptimizationStep)(nil),     // 12: pixly.ai.OptimizationStep
	(*HealthCheckRequest)(nil),   // 13: pixly.ai.HealthCheckRequest
	(*HealthCheckResponse)(nil),  // 14: pixly.ai.HealthCheckResponse
}
var file_proto_ai_service_proto_depIdxs = []int32{
	0,  // 0: pixly.ai.PredictRequest.mode:type_name -> pixly.ai.PredictRequest.Mode
	2,  // 1: pixly.ai.PredictRequest.image:type_name -> pixly.ai.ImageInfo
	3,  // 2: pixly.ai.PredictRequest.options:type_name -> pixly.ai.PredictOptions
	5,  // 3: pixly.ai.PredictResponse.params:type_name -> pixly.ai.ToolParams
	0,  // 4: pixly.ai.PredictBatchRequest.mode:type_name -> pixly.ai.PredictRequest.Mode
	2,  // 5: pixly.ai.PredictBatchRequest.images:type_name -> pixly.ai.ImageInfo
	3,  // 6: pixly.ai.PredictBatchRequest.options:type_name -> pixly.ai.PredictOptions
	4,  // 7: pixly.ai.PredictBatchResponse.results:type_name -> pixly.ai.PredictResponse
	2,  // 8: pixly.ai.OptimizeRequest.image:type_name -> pixly.ai.ImageInfo
	5,  // 9: pixly.ai.OptimizeRequest.initial_params:type_name -> pixly.ai.ToolParams
	5,  // 10: pixly.ai.OptimizeResponse.optimized_params:type_name -> pixly.ai.ToolParams
	12, // 11: pixly.ai.OptimizeResponse.history:type_name -> pixly.ai.OptimizationStep
	5,  // 12: pixly.ai.OptimizationStep.params:type_name -> pixly.ai.ToolParams
	1,  // 13: pixly.ai.AIPredictor.Predict:input_type -> pixly.ai.PredictRequest
	6,  // 14: pixly.ai.AIPredictor.PredictBatch:input_type -> pixly.ai.PredictBatchRequest
	8,  // 15: pixly.ai.AIPredictor.AssessQuality:input_type -> pixly.ai.AssessRequest
	10, // 16: pixly.ai.AIPredictor.OptimizeParams:input_type -> pixly.ai.OptimizeRequest
	13, // 17: pixly.ai.AIPredictor.HealthCheck:input_type -> pixly.ai.HealthCheckRequest
	4,  // 18: pixly.ai.AIPredictor.Predict:output_type -> pixly.ai.PredictResponse
	7,  // 19: pixly.ai.AIPredictor.PredictBatch:output_type -> pixly.ai.PredictBatchResponse
	9,  // 20: pixly.ai.AIPredictor.AssessQuality:output_type -> pixly.ai.AssessResponse
	11, // 21: pixly.ai.AIPredictor.OptimizeParams:output_type -> pixly.ai.OptimizeResponse
	14, // 22: pixly.ai.AIPredictor.HealthCheck:output_type -> pixly.ai.HealthCheckResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_ai_service_proto_init() }
func file_proto_ai_service_proto_init() {
	if File_proto_ai_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_service_proto_rawDesc), len(file_proto_ai_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_service_proto_goTypes,
		DependencyIndexes: file_proto_ai_service_proto_depIdxs,
		EnumInfos:         file_proto_ai_service_proto_enumTypes,
		MessageInfos:      file_proto_ai_service_proto_msgTypes,
	}.Build()
	File_proto_ai_service_proto = out.File
	file_proto_ai_service_proto_goTypes = nil
	file_proto_ai_service_proto_depIdxs = nil
}
