// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/ai_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIPredictor_Predict_FullMethodName        = "/pixly.ai.AIPredictor/Predict"
	AIPredictor_PredictBatch_FullMethodName   = "/pixly.ai.AIPredictor/PredictBatch"
	AIPredictor_AssessQuality_FullMethodName  = "/pixly.ai.AIPredictor/AssessQuality"
	AIPredictor_OptimizeParams_FullMethodName = "/pixly.ai.AIPredictor/OptimizeParams"
	AIPredictor_HealthCheck_FullMethodName    = "/pixly.ai.AIPredictor/HealthCheck"
)

// AIPredictorClient is the client API for AIPredictor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== AI 预测服务 ====================
type AIPredictorClient interface {
	// 预测最优参数（三种模式）
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error)
	// 批量预测
	PredictBatch(ctx context.Context, in *PredictBatchRequest, opts ...grpc.CallOption) (*PredictBatchResponse, error)
	// 质量评估
	AssessQuality(ctx context.Context, in *AssessRequest, opts ...grpc.CallOption) (*AssessResponse, error)
	// 贝叶斯优化参数
	OptimizeParams(ctx context.Context, in *OptimizeRequest, opts ...grpc.CallOption) (*OptimizeResponse, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type aIPredictorClient struct {
	cc grpc.ClientConnInterface
}

func NewAIPredictorClient(cc grpc.ClientConnInterface) AIPredictorClient {
	return &aIPredictorClient{cc}
}

func (c *aIPredictorClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, AIPredictor_Predict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIPredictorClient) PredictBatch(ctx context.Context, in *PredictBatchRequest, opts ...grpc.CallOption) (*PredictBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictBatchResponse)
	err := c.cc.Invoke(ctx, AIPredictor_PredictBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIPredictorClient) AssessQuality(ctx context.Context, in *AssessRequest, opts ...grpc.CallOption) (*AssessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssessResponse)
	err := c.cc.Invoke(ctx, AIPredictor_AssessQuality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIPredictorClient) OptimizeParams(ctx context.Context, in *OptimizeRequest, opts ...grpc.CallOption) (*OptimizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OptimizeResponse)
	err := c.cc.Invoke(ctx, AIPredictor_OptimizeParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIPredictorClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, AIPredictor_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIPredictorServer is the server API for AIPredictor service.
// All implementations must embed UnimplementedAIPredictorServer
// for forward compatibility.
//
// ==================== AI 预测服务 ====================
type AIPredictorServer interface {
	// 预测最优参数（三种模式）
	Predict(context.Context, *PredictRequest) (*PredictResponse, error)
	// 批量预测
	PredictBatch(context.Context, *PredictBatchRequest) (*PredictBatchResponse, error)
	// 质量评估
	AssessQuality(context.Context, *AssessRequest) (*AssessResponse, error)
	// 贝叶斯优化参数
	OptimizeParams(context.Context, *OptimizeRequest) (*OptimizeResponse, error)
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedAIPredictorServer()
}

// UnimplementedAIPredictorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIPredictorServer struct{}

func (UnimplementedAIPredictorServer) Predict(context.Context, *PredictRequest) (*PredictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedAIPredictorServer) PredictBatch(context.Context, *PredictBatchRequest) (*PredictBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PredictBatch not implemented")
}
func (UnimplementedAIPredictorServer) AssessQuality(context.Context, *AssessRequest) (*AssessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssessQuality not implemented")
}
func (UnimplementedAIPredictorServer) OptimizeParams(context.Context, *OptimizeRequest) (*OptimizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OptimizeParams not implemented")
}
func (UnimplementedAIPredictorServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAIPredictorServer) mustEmbedUnimplementedAIPredictorServer() {}
func (UnimplementedAIPredictorServer) testEmbeddedByValue()                     {}

// UnsafeAIPredictorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIPredictorServer will
// result in compilation errors.
type UnsafeAIPredictorServer interface {
	mustEmbedUnimplementedAIPredictorServer()
}

func RegisterAIPredictorServer(s grpc.ServiceRegistrar, srv AIPredictorServer) {
	// If the following call pancis, it indicates UnimplementedAIPredictorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIPredictor_ServiceDesc, srv)
}

func _AIPredictor_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIPredictorServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIPredictor_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIPredictorServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIPredictor_PredictBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIPredictorServer).PredictBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIPredictor_PredictBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIPredictorServer).PredictBatch(ctx, req.(*PredictBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIPredictor_AssessQuality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIPredictorServer).AssessQuality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIPredictor_AssessQuality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIPredictorServer).AssessQuality(ctx, req.(*AssessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIPredictor_OptimizeParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIPredictorServer).OptimizeParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIPredictor_OptimizeParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIPredictorServer).OptimizeParams(ctx, req.(*OptimizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIPredictor_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIPredictorServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIPredictor_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIPredictorServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIPredictor_ServiceDesc is the grpc.ServiceDesc for AIPredictor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIPredictor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pixly.ai.AIPredictor",
	HandlerType: (*AIPredictorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _AIPredictor_Predict_Handler,
		},
		{
			MethodName: "PredictBatch",
			Handler:    _AIPredictor_PredictBatch_Handler,
		},
		{
			MethodName: "AssessQuality",
			Handler:    _AIPredictor_AssessQuality_Handler,
		},
		{
			MethodName: "OptimizeParams",
			Handler:    _AIPredictor_OptimizeParams_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _AIPredictor_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ai_service.proto",
}
